CREATE TABLE [dbo].[PERSONA]
(
[IDPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APEPER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIRPER] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNIPER] [numeric] (18, 0) NULL,
[TELPER] [numeric] (18, 0) NULL,
[EMAIL] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPPER] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESTPER] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PERSONA_ESTPER] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PERSONA_pk] PRIMARY KEY CLUSTERED  ([IDPER]) ON [PRIMARY]
GO
