CREATE TABLE [dbo].[MASCOTA]
(
[IDMAS] [int] NOT NULL IDENTITY(1, 1),
[NOMMAS] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECMAS] [date] NULL,
[TIPMAS] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RAZMAS] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PESMAS] [numeric] (18, 0) NULL,
[IDPER] [int] NOT NULL,
[ESTMAS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MASCOTA_ESTMAS] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MASCOTA] ADD CONSTRAINT [MASCOTA_pk] PRIMARY KEY CLUSTERED  ([IDMAS]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MASCOTA] ADD CONSTRAINT [FK_MASCOTA_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
