CREATE TABLE [dbo].[SERVICIO]
(
[IDSERV] [int] NOT NULL IDENTITY(1, 1),
[NOMSERV] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRSERV] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COSTSERV] [numeric] (18, 0) NULL,
[IDDETSERV] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SERVICIO] ADD CONSTRAINT [SERVICIO_pk] PRIMARY KEY CLUSTERED  ([IDSERV]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SERVICIO] ADD CONSTRAINT [FK_SERVICIO_DETALLESERVICIO] FOREIGN KEY ([IDDETSERV]) REFERENCES [dbo].[DETALLESERVICIO] ([IDDETSERV])
GO
