CREATE TABLE [dbo].[MEDICINA]
(
[IDMED] [int] NOT NULL IDENTITY(1, 1),
[NOMMED] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRECMED] [money] NULL,
[DOSMED] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECPROMED] [date] NULL,
[FECVENMED] [date] NULL,
[DISPMED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_MEDICINA_DISPMED] DEFAULT ('D')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEDICINA] ADD CONSTRAINT [MEDICINA_pk] PRIMARY KEY CLUSTERED  ([IDMED]) ON [PRIMARY]
GO
