CREATE TABLE [dbo].[HISTORIACLINICA]
(
[IDHCLIN] [int] NOT NULL IDENTITY(1, 1),
[ESTCLIN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECAPERCLIN] [timestamp] NULL,
[IDMAS] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORIACLINICA] ADD CONSTRAINT [HISTORIACLINICA_pk] PRIMARY KEY CLUSTERED  ([IDHCLIN]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORIACLINICA] ADD CONSTRAINT [FK_HISTORIACLINICA_MASCOTA] FOREIGN KEY ([IDMAS]) REFERENCES [dbo].[MASCOTA] ([IDMAS])
GO
