CREATE TABLE [dbo].[PRODUCTO]
(
[IDPRO] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRECOMPPRO] [numeric] (18, 0) NULL,
[PREVENTPRO] [numeric] (18, 0) NULL,
[CANTPRO] [int] NULL,
[FCADPRO] [date] NULL,
[TIPPRO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DISPPRO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PRODUCTO_DISPPRO] DEFAULT ('D')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED  ([IDPRO]) ON [PRIMARY]
GO
