CREATE TABLE [dbo].[USUARIOS]
(
[IDUSU] [int] NOT NULL IDENTITY(1, 1),
[USUA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTRA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIVUSU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDPER] [int] NOT NULL,
[ESTUSU] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_USUARIOS_ESTUSU] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIOS] ADD CONSTRAINT [USUARIOS_pk] PRIMARY KEY CLUSTERED  ([IDUSU]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIOS] ADD CONSTRAINT [FK_USUARIOS_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
