CREATE TABLE [dbo].[BOLETA]
(
[NUMBOL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FECHA] [date] NULL,
[IDPER] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOLETA] ADD CONSTRAINT [BOLETA_pk] PRIMARY KEY CLUSTERED  ([NUMBOL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOLETA] ADD CONSTRAINT [FK_BOLETA_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
